FROM gregoryguillou/terraform-deck:latest-demo

ARG GITHUB_REPOSITORY=https://github.com/gregoryguillou/terraform-deck-stacks.git
ARG CACHEBUST=1

RUN git clone ${GITHUB_REPOSITORY} /github/repository
